# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Glaenta
email: jolundq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Swedish word "glänta" is used for a small opening in a forest ("glade" in English), but it can also be used as a verb that means to slightly move an object - usually a door, curtain, or something of the like - in order to get a peek of what is on the other side of it.

  The word is often used in metaphors for the act of entering and getting a glimpse of new and previously unknown territory of knowlege.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://you1.se" # the base hostname & protocol for your site
url: "http://you1.se" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  youone

# Build settings
markdown: kramdown
theme: minima
