title: Johan Lundquist
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://you1.se" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Johan Lundquist # add your name
author-img: johan_color_mini2.jpg # add your photo
about-author: I am a physicist, systems engineer and web developer with a background in particle physics research and with a keen interest also in history, art and socio-economic questions. Constantly searching for new knowledge and perspectives. # add description
#social-twitter: # add your Twitter handle
social-facebook: johan.lundquist.75
social-github: youone # add your Github handle
#social-linkedin: youone
social-email: jolundq@gmail.com

# Disqus
discus-identifier: you1 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Sharing debugger
# https://developers.facebook.com/tools/debug/sharing/
